### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by armaneshaghi** [cookpa/pipedream#1]
Pipedream has been  mentioned in several studies from ANTs core developers, in the recent ANTs manual as an automation tool for neuroimaging pipelines, and  therefore sounds really promising. It would help other users to have a summary (or an introduction) of its usage as the Readme file in github, it could attract more users or contributors, as the current usage of pipedream for someone completely new is vague and impossible.

**Comment by cookpa** [comment]
Hi @armaneshaghi ,

You are right, the documentation is not up to par. The T1 cortical thickness / DTI normalization algorithm that was run in papers referencing Pipedream is contained in the file experimental/antsbrainprocessing.sh. It is written for the older (pre ITK V4) ANTs tools. 

We have now stopped maintaining that script, there is an improved cortical thickness pipeline that is available in ANTs as Scripts/antsCorticalThickness.sh. It should be easier to follow than antsbrainprocessing and has a similar workflow (T1 brain extraction, tissue segmentation, template registration and cortical thickness). It also has a command line interface that doesn't require any config files. We're working on a system for multiple modalities that make use of the T1 for brain extraction and normalization much as antsbrainprocessing does for DTI. That's available in ANTs as Scripts/antsNeuroimagingBattery. It's more of a work in progress than antsCorticalThickness.

There's more information on antsCorticalThickness, and how to build the required templates, over at the ANTs site.
