### ISSUE TITLE
Question about dicom2nii.pl

### ISSUE THREAD

**Issue by ntustison** [cookpa/pipedream#5]
Hey @cookpa,

What is the second part of [this](https://github.com/cookpa/pipedream/blob/master/dicom2nii/dicom2nii.pl#L98) if statement checking?

``m|^([0-9]+_${protocolName})/?$|m``

**Comment by cookpa** [comment]
It's checking for series of the format 

0000_seriesName

As produced by dicom2series, which keeps the series numbers so that repeat acquisitions are listed separately. You could modify it to allow an exact match with the protocol name.

**Comment by ntustison** [comment]
That's what I thought.  I must be doing something else wrong.  Thanks.
